/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import dao.active_parking_dao;
import model.active_parking_model;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyber
 */
public class active_panel extends javax.swing.JPanel {
        private final active_parking_dao activeParkingDAO = new active_parking_dao();
        private Timer refreshTimer;

        public active_panel() {
                initComponents();
                configureActivePanel();
                loadActiveParking();
                startRefreshTimer();
                refreshData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                content_panel = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                txt_search = new javax.swing.JTextField();
                btn_search = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbl_active = new javax.swing.JTable();
                lbl_active_count = new javax.swing.JLabel();
                btn_refresh = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                content_panel.setBackground(new java.awt.Color(0, 0, 0));
                content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                txt_search.addActionListener(this::txt_searchActionPerformed);
                jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 30));

                btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_search.setText("Search ");
                btn_search.addActionListener(this::btn_searchActionPerformed);
                jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, 30));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel2.setText("Search Query");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, -1));

                content_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 70));

                tbl_active.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String [] {
                        "Id", "Registration", "Customer", "Type", "Space", "Entry Time", "Duration"
                }
                ) {
                boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                }
                });
                tbl_active.getTableHeader().setReorderingAllowed(false);
                jScrollPane1.setViewportView(tbl_active);
                if (tbl_active.getColumnModel().getColumnCount() > 0) {
                        tbl_active.getColumnModel().getColumn(0).setResizable(false);
                        tbl_active.getColumnModel().getColumn(1).setResizable(false);
                        tbl_active.getColumnModel().getColumn(2).setResizable(false);
                        tbl_active.getColumnModel().getColumn(3).setResizable(false);
                        tbl_active.getColumnModel().getColumn(4).setResizable(false);
                        tbl_active.getColumnModel().getColumn(5).setResizable(false);
                        tbl_active.getColumnModel().getColumn(6).setResizable(false);
                }

                content_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 700, 300));

                lbl_active_count.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbl_active_count.setForeground(new java.awt.Color(255, 255, 255));
                content_panel.add(lbl_active_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 160, 30));

                btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_refresh.setText("Refresh ");
                btn_refresh.addActionListener(this::btn_refreshActionPerformed);
                content_panel.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("ACTIVE");
                content_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

                add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
        }// </editor-fold>//GEN-END:initComponents

        private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {
                searchActiveParking();
        }

        private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {
                searchActiveParking();
        }

        private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {
        refreshData();

    }

        private void configureActivePanel() {
                tbl_active.getTableHeader().setReorderingAllowed(false);
                tbl_active.setRowHeight(25);
        }
    
        private void loadActiveParking() {
                List<active_parking_model> active_parking_list = activeParkingDAO.get_all_active_parking();
                displayActiveParking(active_parking_list);
                updateActiveCount(active_parking_list.size());
        }
    
        private void displayActiveParking(List<active_parking_model> active_parking_list) {
                DefaultTableModel table_model = (DefaultTableModel) tbl_active.getModel();
                table_model.setRowCount(0);
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

                for (active_parking_model active_parking : active_parking_list) {
                        String entry_time = active_parking.get_active_parking_entry_time().format(formatter);
                        String duration = calculateDuration(active_parking.get_active_parking_entry_time());

                        table_model.addRow(new Object[]{ active_parking.get_active_parking_session_id(), active_parking.get_active_parking_registration_number(), active_parking.get_active_parking_customer_name(), active_parking.get_active_parking_vehicle_type(), active_parking.get_active_parking_space_number(), entry_time, duration });
                }
        }
    
        private String calculateDuration(LocalDateTime entry_time) {
                LocalDateTime current_time = LocalDateTime.now();

                if (entry_time.isAfter(current_time)) {
                        return "0h 0m";
                }

                Duration duration = Duration.between(entry_time, current_time);
                long total_minutes = duration.toMinutes();
                long hours = total_minutes / 60;
                long minutes = total_minutes % 60;

                return hours + "h " + minutes + "m";
        }
    
        private void updateActiveCount(int count) {
                lbl_active_count.setText("Active Sessions: " + count);
        }
    
        private void searchActiveParking() {
                String keyword = txt_search.getText().trim();

                if (keyword.isEmpty()) {
                        loadActiveParking();
                        return;
                }

                List<active_parking_model> active_parking_list = activeParkingDAO.search_active_parking(keyword);
                displayActiveParking(active_parking_list);
                updateActiveCount(active_parking_list.size());
        }
    
        public void refreshData() {
                txt_search.setText("");
                loadActiveParking();
        }
    
        private void startRefreshTimer() {
                refreshTimer = new Timer(5000, evt -> {
                        if (isShowing()) {
                                refreshCurrentView();
                        }
                });
                refreshTimer.start();
        }
    
        private void refreshCurrentView() {
                String keyword = txt_search.getText().trim();

                if (keyword.isEmpty()) {
                        loadActiveParking();
                        return;
                }

                List<active_parking_model> active_parking_list = activeParkingDAO.search_active_parking(keyword);
                displayActiveParking(active_parking_list);
                updateActiveCount(active_parking_list.size());
        }
    
        private void updateActiveCount() {
                int count = activeParkingDAO.get_all_active_parking().size();
                lbl_active_count.setText("Active Sessions: " + count);
        }
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_refresh;
        private javax.swing.JButton btn_search;
        private javax.swing.JPanel content_panel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lbl_active_count;
        private javax.swing.JTable tbl_active;
        private javax.swing.JTextField txt_search;
        // End of variables declaration//GEN-END:variables
}
