/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;
import dao.customer_dao;
import model.customer_model;

/**
 *
 * @author cyber
 */
public class customers_panel extends javax.swing.JPanel {
    private final customer_dao customerDAO = new customer_dao();
    private boolean editMode = false;
    private int selectedCustomerId = -1;

    public customers_panel() {
        initComponents();
        configureCustomerPanel();
        configureCustomerDialog();
        configureEvents();
        loadCustomers();
        refreshData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 360, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("Save");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Address");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jDialog1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Search Query");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, -1));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(this::btn_searchActionPerformed);
        jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone", "Email", "Registered"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 700, 300));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 80, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 90, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Edit");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CUSTOMERS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        openAddCustomerDialog();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        openEditCustomerDialog();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = jTextField1.getText().trim();

        if (keyword.isEmpty()) {
            refreshData();
        } else {
            searchCustomers();
        }
    }                                          

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {
        searchCustomers();
    }                                        

    private void configureCustomerPanel() {
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setRowHeight(25);
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);
    }

    private void configureCustomerDialog() {
        jDialog1.setModal(true);
        jDialog1.setResizable(false);
        jDialog1.setTitle("Customer");
        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    private void configureEvents() {
        jButton3.addActionListener(evt -> deleteCustomer());
        // jButton6 is Cancel and jButton7 is Save in the generated form.
        jButton6.addActionListener(evt -> closeCustomerDialog());
        jButton7.addActionListener(evt -> saveCustomer());
        jTable1.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                boolean selected = jTable1.getSelectedRow() != -1;
                jButton4.setEnabled(selected);
                jButton3.setEnabled(selected);
            }
        });
    }

    private void loadCustomers() {
        List<customer_model> customers = customerDAO.getAllCustomers();
        displayCustomers(customers);
    }

    private void displayCustomers(List<customer_model> customers) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        tableModel.setRowCount(0);

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");

        for (customer_model customer : customers) {
            Timestamp createdAt = customer.get_customer_model_createdAt();
            String registered = "";

            if (createdAt != null) {
                registered = dateFormat.format(createdAt);
            }

            tableModel.addRow(new Object[]{
                customer.get_customer_model_customer_id(),
                customer.get_customer_model_name(),
                customer.get_customer_model_phone(),
                customer.get_customer_model_email(),
                registered
            });
        }
        jTable1.clearSelection();
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);
    }

    private void openAddCustomerDialog() {

        editMode = false;

        selectedCustomerId = -1;

        clearCustomerForm();

        jDialog1.setTitle("Add Customer");
        jButton7.setText("Save");
        jDialog1.setSize(420, 340);
        jDialog1.setLocationRelativeTo(this);
        jTextField2.requestFocusInWindow();
        jDialog1.setVisible(true);
    }

    private void openEditCustomerDialog() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a customer first.", "No Customer Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            selectedCustomerId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid customer ID.", "Customer Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String name = getTableValue(selectedRow, 1);
        String phone = getTableValue(selectedRow, 2);
        String email = getTableValue(selectedRow, 3);

        editMode = true;

        jTextField2.setText(name);
        jTextField3.setText(phone);
        jTextField4.setText(email);
        jDialog1.setTitle("Edit Customer");
        jButton7.setText("Update");
        jDialog1.setSize(420, 340);
        jDialog1.setLocationRelativeTo(this);
        jTextField2.requestFocusInWindow();
        jDialog1.setVisible(true);
    }

    private void saveCustomer() {
        String name = jTextField2.getText().trim();
        String phone = jTextField3.getText().trim();
        String email = jTextField4.getText().trim();

        if (name.isEmpty()) {
            showValidationError("Customer name is required.", jTextField2);
            return;
        }

        if (name.length() < 2) {
            showValidationError("Customer name must contain at least 2 characters.", jTextField2);
            return;
        }

        // if (!name.matches("[A-Za-z ]+")) {
        //     showValidationError("Customer name can only contain letters and spaces.", jTextField2);
        //     return;
        // }

        if (phone.isEmpty()) {
            showValidationError("Phone number is required.", jTextField3);
            return;
        }

        // if (!phone.matches("\\+?[0-9]{7,15}")) {
        //     showValidationError("Enter a valid phone number.", jTextField3);
        //     return;
        // }

        if (email.isEmpty()) {
            showValidationError("Email address is required.", jTextField4);
            return;
        }

        // if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
        //     showValidationError("Enter a valid email address.", jTextField4);
        //     return;
        // }

        Integer excludedCustomerId = editMode ? selectedCustomerId : null;
        boolean emailExists = customerDAO.emailExists(email, excludedCustomerId);

        if (emailExists) {
            showValidationError("This email address is already registered.", jTextField4);
            return;
        }

        if (editMode) {
            updateCustomer(name, phone, email);
        } else {
            addCustomer(name, phone, email);
        }
    }

    private void addCustomer(String name, String phone, String email) {
        customer_model customer = new customer_model(name, phone, email);
        boolean success = customerDAO.addCustomer(customer);

        if (success) {
            JOptionPane.showMessageDialog(jDialog1, "Customer added successfully.", "Add Customer", JOptionPane.INFORMATION_MESSAGE);

            closeCustomerDialog();
            loadCustomers();
        } else {
            JOptionPane.showMessageDialog(jDialog1, "Unable to add customer.\n" + "Check the database connection " + "and customer information.", "Add Customer Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateCustomer(String name, String phone, String email) {
        customer_model existingCustomer = customerDAO.getCustomerById(selectedCustomerId);

        if (existingCustomer == null) {
            JOptionPane.showMessageDialog(jDialog1, "Customer could not be found.", "Update Customer", JOptionPane.ERROR_MESSAGE);
            return;
        }

        customer_model customer = new customer_model(selectedCustomerId, name, phone, email, existingCustomer.get_customer_model_createdAt());
        boolean success = customerDAO.updateCustomer(customer);

        if (success) {
            JOptionPane.showMessageDialog(jDialog1, "Customer updated successfully.", "Update Customer", JOptionPane.INFORMATION_MESSAGE);

            closeCustomerDialog();
            loadCustomers();
        } else {
            JOptionPane.showMessageDialog(jDialog1, "Unable to update customer.", "Update Customer Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteCustomer() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a customer first.", "No Customer Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int customerId;

        try {
            customerId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid customer ID.", "Delete Customer", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String customerName = getTableValue(selectedRow, 1);
        if (customerDAO.customerHasActiveParking(customerId)) {
            JOptionPane.showMessageDialog(this,
                    "Cannot delete " + customerName + ".\n\nA vehicle owned by this customer is currently parked. Complete its exit first.",
                    "Customer Has Active Parking", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmation = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to permanently delete " + customerName + "?\n\n"
                + "All vehicles and completed parking history for this customer will also be deleted.",
                "Delete Customer", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmation != JOptionPane.YES_OPTION) {
            return;
        }

        boolean success = customerDAO.deleteCustomer(customerId);
        if (success) {
            JOptionPane.showMessageDialog(this, "Customer deleted successfully.", "Delete Customer", JOptionPane.INFORMATION_MESSAGE);

            loadCustomers();
        } else {
            JOptionPane.showMessageDialog(this, "Unable to delete customer.\n"
                    + "The customer may still have active parking, or the database operation failed.",
                    "Delete Customer Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchCustomers() {
        String keyword = jTextField1.getText().trim();
        List<customer_model> customers;

        if (keyword.isEmpty()) {
            customers = customerDAO.getAllCustomers();
        } else {
            customers = customerDAO.searchCustomers(keyword);
        }

        displayCustomers(customers);
    }

    private void showValidationError(String message, javax.swing.JTextField field) {
        JOptionPane.showMessageDialog(jDialog1, message, "Validation Error", JOptionPane.WARNING_MESSAGE);

        field.requestFocusInWindow();
    }

    private String getTableValue(int row, int column) {
        Object value = jTable1.getValueAt(row, column);
        if (value == null) {
            return "";
        }

        return value.toString();
    }

    private void clearCustomerForm() {
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }

    private void closeCustomerDialog() {
        jDialog1.setVisible(false);
        clearCustomerForm();
        editMode = false;
        selectedCustomerId = -1;
    }

    public void refreshData() {
        jTextField1.setText("");
        loadCustomers();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
