/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import dao.history_dao;
import model.history_model;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyber
 */
public class history_panel extends javax.swing.JPanel {
        private final history_dao historyDAO = new history_dao();

        public history_panel() {
                initComponents();
                configureHistoryPanel();
                loadHistory();
                refreshData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                content_panel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbl_history = new javax.swing.JTable();
                btn_refresh = new javax.swing.JButton();
                lbl_history_count = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                txt_search = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                btn_search = new javax.swing.JButton();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                content_panel.setBackground(new java.awt.Color(0, 0, 0));
                content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                tbl_history.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "ID ", "Vehicle ", "Customer ", "Type ", "Space ", "Entry ", "Exit ", "Duration ", "Fee     "
                }
                ) {
                boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                }
                });
                jScrollPane1.setViewportView(tbl_history);
                if (tbl_history.getColumnModel().getColumnCount() > 0) {
                tbl_history.getColumnModel().getColumn(0).setResizable(false);
                tbl_history.getColumnModel().getColumn(1).setResizable(false);
                tbl_history.getColumnModel().getColumn(2).setResizable(false);
                tbl_history.getColumnModel().getColumn(3).setResizable(false);
                tbl_history.getColumnModel().getColumn(4).setResizable(false);
                tbl_history.getColumnModel().getColumn(5).setResizable(false);
                tbl_history.getColumnModel().getColumn(6).setResizable(false);
                tbl_history.getColumnModel().getColumn(7).setResizable(false);
                tbl_history.getColumnModel().getColumn(8).setResizable(false);
                }

                content_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 700, 300));

                btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_refresh.setText("Refresh");
                btn_refresh.addActionListener(this::btn_refreshActionPerformed);
                content_panel.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

                lbl_history_count.setForeground(new java.awt.Color(255, 255, 255));
                content_panel.add(lbl_history_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 30));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("HISTORY");
                content_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                txt_search.addActionListener(this::txt_searchActionPerformed);
                jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 30));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setText("Search Query");
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, -1));

                btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_search.setText("Search");
                btn_search.addActionListener(this::btn_searchActionPerformed);
                jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 90, 30));

                content_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 70));

                add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
        }// </editor-fold>//GEN-END:initComponents

        private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
                // TODO add your handling code here:
                searchHistory();

        }//GEN-LAST:event_btn_searchActionPerformed

        private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        
    loadHistory();

    }//GEN-LAST:event_btn_refreshActionPerformed

        private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_searchActionPerformed

        private void configureHistoryPanel() {

        tbl_history
                .getTableHeader()
                .setReorderingAllowed(false);

        tbl_history.setRowHeight(25);
        }
        
        private void loadHistory() {

    List<history_model> history_list =
            historyDAO
                    .get_all_history();


    displayHistory(
            history_list
    );


    updateHistoryCount();
}
    
        private void displayHistory(
                List<history_model> history_list) {

        DefaultTableModel table_model =
                (DefaultTableModel)
                        tbl_history.getModel();


        table_model.setRowCount(0);


        DateTimeFormatter formatter =
                DateTimeFormatter.ofPattern(
                        "yyyy-MM-dd HH:mm:ss"
                );


        for (history_model history
                : history_list) {


                String entry_time =
                        history
                                .get_history_entry_time()
                                .format(formatter);


                String exit_time =
                        history
                                .get_history_exit_time()
                                .format(formatter);


                String duration =
                        calculateDuration(
                                history
                                        .get_history_entry_time(),

                                history
                                        .get_history_exit_time()
                        );


                String hourly_rate =
                        history
                                .get_history_hourly_rate()
                                .setScale(
                                        2,
                                        RoundingMode.HALF_UP
                                )
                                .toPlainString();


                String parking_fee =
                        history
                                .get_history_parking_fee()
                                .setScale(
                                        2,
                                        RoundingMode.HALF_UP
                                )
                                .toPlainString();


                table_model.addRow(
                        new Object[]{

                        history
                                .get_history_session_id(),

                        history
                                .get_history_registration_number(),

                        history
                                .get_history_customer_name(),

                        history
                                .get_history_vehicle_type(),

                        history
                                .get_history_space_number(),

                        entry_time,

                        exit_time,

                        duration,

                        hourly_rate,

                        parking_fee
                        }
                );
        }
        }
        
        private String calculateDuration(
                LocalDateTime entry_time,
                LocalDateTime exit_time) {


        if (entry_time == null
                || exit_time == null) {

                return "-";
        }


        if (exit_time.isBefore(entry_time)) {

                return "0h 0m";
        }


        Duration duration =
                Duration.between(
                        entry_time,
                        exit_time
                );


        long total_minutes =
                duration.toMinutes();


        long hours =
                total_minutes / 60;


        long minutes =
                total_minutes % 60;


        return hours
                + "h "
                + minutes
                + "m";
        }
        
        public void refreshData() {

        txt_search.setText("");

        loadHistory();
        }

        private void updateHistoryCount() {

        int count =
                historyDAO.get_history_count();

        lbl_history_count.setText(
                "Completed Sessions: " + count
        );
        }
        
        private void searchHistory() {

    String keyword =
            txt_search
                    .getText()
                    .trim();


    if (keyword.isEmpty()) {

        loadHistory();

        return;
    }


    List<history_model> history_list =
            historyDAO
                    .search_history(
                            keyword
                    );


    displayHistory(
            history_list
    );


    updateHistoryCount();
}
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_refresh;
        private javax.swing.JButton btn_search;
        private javax.swing.JPanel content_panel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lbl_history_count;
        private javax.swing.JTable tbl_history;
        private javax.swing.JTextField txt_search;
        // End of variables declaration//GEN-END:variables
}