/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import dao.park_vehicle_dao;
import model.parking_session_model;
import model.parking_space_model;
import model.vehicle_model;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author cyber
 */
public class park_vehicle_panel extends javax.swing.JPanel {
        private final park_vehicle_dao parkVehicleDAO = new park_vehicle_dao();
        private List<vehicle_model> vehicleList = new ArrayList<>();
        private List<parking_space_model> spaceList = new ArrayList<>();

        public park_vehicle_panel() {
                initComponents();
                configurePanel();
                loadVehicles();
                updateEntryTime();
                refreshData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                content_panel = new javax.swing.JPanel();
                cmb_vehicle = new javax.swing.JComboBox<>();
                txt_vehicle_type = new javax.swing.JTextField();
                txt_owner = new javax.swing.JTextField();
                cmb_space = new javax.swing.JComboBox<>();
                txt_hourly_rate = new javax.swing.JTextField();
                txt_entry_time = new javax.swing.JTextField();
                btn_clear = new javax.swing.JButton();
                btn_park_vehicle = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                content_panel.setBackground(new java.awt.Color(0, 0, 0));
                content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                cmb_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                cmb_vehicle.addActionListener(this::cmb_vehicleActionPerformed);
                content_panel.add(cmb_vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 320, 30));

                txt_vehicle_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                txt_vehicle_type.addActionListener(this::txt_vehicle_typeActionPerformed);
                content_panel.add(txt_vehicle_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, -1));

                txt_owner.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                txt_owner.addActionListener(this::txt_ownerActionPerformed);
                content_panel.add(txt_owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 320, -1));

                cmb_space.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                cmb_space.addActionListener(this::cmb_spaceActionPerformed);
                content_panel.add(cmb_space, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 320, -1));

                txt_hourly_rate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                txt_hourly_rate.addActionListener(this::txt_hourly_rateActionPerformed);
                content_panel.add(txt_hourly_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 320, -1));

                txt_entry_time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                txt_entry_time.addActionListener(this::txt_entry_timeActionPerformed);
                content_panel.add(txt_entry_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 320, -1));

                btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_clear.setText("Clear");
                btn_clear.addActionListener(this::btn_clearActionPerformed);
                content_panel.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 110, -1));

                btn_park_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_park_vehicle.setText("Park");
                btn_park_vehicle.addActionListener(this::btn_park_vehicleActionPerformed);
                content_panel.add(btn_park_vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 110, -1));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("PARK");
                content_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Entry Time");
                content_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 100, -1));

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Vehicle");
                content_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Vehicle Type");
                content_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Hourly Rate");
                content_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, -1));

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Available Parking Space");
                content_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 210, -1));

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Owner");
                content_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 100, -1));

                add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
        }// </editor-fold>//GEN-END:initComponents

        private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
                // TODO add your handling code here:
                clearForm();

        }//GEN-LAST:event_btn_clearActionPerformed

        private void btn_park_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_park_vehicleActionPerformed
                // TODO add your handling code here:
                parkVehicle();
        }//GEN-LAST:event_btn_park_vehicleActionPerformed

        private void txt_entry_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_entry_timeActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_entry_timeActionPerformed

        private void txt_hourly_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hourly_rateActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_hourly_rateActionPerformed

        private void cmb_spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_spaceActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_cmb_spaceActionPerformed

        private void txt_vehicle_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vehicle_typeActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_vehicle_typeActionPerformed

        private void cmb_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_vehicleActionPerformed
                // TODO add your handling code here:
                vehicleSelectionChanged();
        }//GEN-LAST:event_cmb_vehicleActionPerformed

        private void txt_ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ownerActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_ownerActionPerformed

        private void configurePanel() {

        txt_vehicle_type.setEditable(false);
        txt_owner.setEditable(false);
        txt_entry_time.setEditable(false);

        txt_vehicle_type.setText("");
        txt_owner.setText("");
        txt_entry_time.setText("");

        txt_hourly_rate.setText("");

        cmb_vehicle.removeAllItems();
        cmb_space.removeAllItems();
        }
        
        private void loadVehicles() {

        vehicleList =
                parkVehicleDAO.getAvailableVehicles();

        cmb_vehicle.removeAllItems();

        cmb_vehicle.addItem(
                "-- Select Vehicle --"
        );

        for (vehicle_model vehicle
                : vehicleList) {

                String display =
                        vehicle.getRegistration_number()
                        + " - "
                        + vehicle.getBrand()
                        + " "
                        + vehicle.getModel();

                cmb_vehicle.addItem(display);
        }

        cmb_vehicle.setSelectedIndex(0);

        clearVehicleDetails();
        }
        
        private void vehicleSelectionChanged() {

        int selectedIndex =
                cmb_vehicle.getSelectedIndex();

        /*
        * index 0 = "-- Select Vehicle --"
        *
        * Therefore actual List index is
        * selectedIndex - 1.
        */
        if (selectedIndex <= 0) {

                clearVehicleDetails();

                cmb_space.removeAllItems();

                cmb_space.addItem(
                        "-- Select Space --"
                );

                return;
        }

        vehicle_model vehicle =
                vehicleList.get(
                        selectedIndex - 1
                );

        txt_vehicle_type.setText(
                vehicle.getVehicle_type()
        );

        txt_owner.setText(
                vehicle.getCustomer_name()
        );

        loadAvailableSpaces(
                vehicle.getVehicle_type()
        );
        }
        
        private void loadAvailableSpaces(
                String vehicleType) {

        spaceList =
                parkVehicleDAO
                        .getAvailableSpacesByType(
                                vehicleType
                        );

        cmb_space.removeAllItems();

        cmb_space.addItem(
                "-- Select Space --"
        );

        for (parking_space_model space
                : spaceList) {

                cmb_space.addItem(
                        space.getSpace_number()
                );
        }

        cmb_space.setSelectedIndex(0);
        }
        
        private void updateEntryTime() {

        Timestamp now =
                new Timestamp(
                        System.currentTimeMillis()
                );

        SimpleDateFormat format =
                new SimpleDateFormat(
                        "yyyy-MM-dd HH:mm:ss"
                );

        txt_entry_time.setText(
                format.format(now)
        );
        }
        
        private void parkVehicle() {

        int vehicleIndex =
                cmb_vehicle.getSelectedIndex();

        if (vehicleIndex <= 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select a vehicle.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        int spaceIndex =
                cmb_space.getSelectedIndex();

        if (spaceIndex <= 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select an available parking space.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        String rateText =
                txt_hourly_rate
                        .getText()
                        .trim();

        if (rateText.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Hourly rate is required.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                txt_hourly_rate.requestFocusInWindow();

                return;
        }


        BigDecimal hourlyRate;

        try {

                hourlyRate =
                        new BigDecimal(
                                rateText
                        );

        } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "Enter a valid hourly rate.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                txt_hourly_rate.requestFocusInWindow();

                return;
        }


        if (hourlyRate.compareTo(
                BigDecimal.ZERO) <= 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Hourly rate must be greater than 0.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        if (hourlyRate.scale() > 2) {

                JOptionPane.showMessageDialog(
                        this,
                        "Hourly rate can have a maximum of 2 decimal places.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        vehicle_model vehicle =
                vehicleList.get(
                        vehicleIndex - 1
                );

        parking_space_model space =
                spaceList.get(
                        spaceIndex - 1
                );


        Timestamp entryTime =
                new Timestamp(
                        System.currentTimeMillis()
                );


        int confirmation =
                JOptionPane.showConfirmDialog(
                        this,
                        "Park vehicle "
                        + vehicle.getRegistration_number()
                        + " in space "
                        + space.getSpace_number()
                        + "?\n\n"
                        + "Type: "
                        + vehicle.getVehicle_type()
                        + "\n"
                        + "Hourly Rate: "
                        + hourlyRate.toPlainString(),
                        "Confirm Parking",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

        if (confirmation
                != JOptionPane.YES_OPTION) {

                return;
        }


        parking_session_model session =
                new parking_session_model(
                        vehicle.getVehicle_id(),
                        space.getSpace_id(),
                        entryTime,
                        hourlyRate
                );


        boolean success =
                parkVehicleDAO.parkVehicle(
                        session
                );


        if (success) {

                JOptionPane.showMessageDialog(
                        this,
                        "Vehicle parked successfully.\n\n"
                        + "Vehicle: "
                        + vehicle.getRegistration_number()
                        + "\n"
                        + "Space: "
                        + space.getSpace_number(),
                        "Parking Successful",
                        JOptionPane.INFORMATION_MESSAGE
                );

                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Unable to park the vehicle.\n\n"
                        + "The vehicle may already be parked "
                        + "or the selected space may no longer be available.",
                        "Parking Failed",
                        JOptionPane.ERROR_MESSAGE
                );

                refreshData();
        }
        }
        
        private void clearForm() {

        if (cmb_vehicle.getItemCount() > 0) {
                cmb_vehicle.setSelectedIndex(0);
        }

        cmb_space.removeAllItems();

        cmb_space.addItem(
                "-- Select Space --"
        );

        txt_vehicle_type.setText("");
        txt_owner.setText("");
        txt_hourly_rate.setText("");

        updateEntryTime();
        }
        
        private void clearVehicleDetails() {

        txt_vehicle_type.setText("");
        txt_owner.setText("");
        }
        
        public void refreshData() {

        loadVehicles();

        cmb_space.removeAllItems();

        cmb_space.addItem(
                "-- Select Space --"
        );

        txt_vehicle_type.setText("");
        txt_owner.setText("");
        txt_hourly_rate.setText("");

        updateEntryTime();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_clear;
        private javax.swing.JButton btn_park_vehicle;
        private javax.swing.JComboBox<String> cmb_space;
        private javax.swing.JComboBox<String> cmb_vehicle;
        private javax.swing.JPanel content_panel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JTextField txt_entry_time;
        private javax.swing.JTextField txt_hourly_rate;
        private javax.swing.JTextField txt_owner;
        private javax.swing.JTextField txt_vehicle_type;
        // End of variables declaration//GEN-END:variables
}