/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import dao.parking_space_dao;
import model.parking_space_model;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyber
 */
public class spaces_panel extends javax.swing.JPanel {
        private final parking_space_dao spaceDAO = new parking_space_dao();
        private boolean editMode = false;
        private int selectedSpaceId = -1;

        public spaces_panel() {
                initComponents();
                configureSpacePanel();
                configureSpaceDialog();
                configureEvents();
                loadSpaces();
                refreshData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        space_dialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        txt_space_number = new javax.swing.JTextField();
        cmb_space_type = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_spaces = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();

        space_dialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_space_number.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_space_number.addActionListener(this::txt_space_numberActionPerformed);
        jPanel2.add(txt_space_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        cmb_space_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmb_space_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAR", "MOTORCYCLE", "VAN" }));
        cmb_space_type.addActionListener(this::cmb_space_typeActionPerformed);
        jPanel2.add(cmb_space_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, -1));

        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(this::btn_cancelActionPerformed);
        jPanel2.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(this::btn_saveActionPerformed);
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Space Type");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Space Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        space_dialog.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 300));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content_panel.setBackground(new java.awt.Color(0, 0, 0));
        content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_spaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "Space Number", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_spaces);
        if (tbl_spaces.getColumnModel().getColumnCount() > 0) {
            tbl_spaces.getColumnModel().getColumn(0).setResizable(false);
            tbl_spaces.getColumnModel().getColumn(1).setResizable(false);
            tbl_spaces.getColumnModel().getColumn(2).setResizable(false);
            tbl_spaces.getColumnModel().getColumn(3).setResizable(false);
        }

        content_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 700, 300));

        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_delete.setText("delete");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);
        content_panel.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_edit.setText("edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);
        content_panel.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setText("add");
        btn_add.addActionListener(this::btn_addActionPerformed);
        content_panel.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SPACES");
        content_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.addActionListener(this::txt_searchActionPerformed);
        jPanel3.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Search Query");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, -1));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(this::btn_searchActionPerformed);
        jPanel3.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 90, 30));

        content_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 70));

        add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
    }// </editor-fold>//GEN-END:initComponents

        private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {
        searchSpaces();
        }

        private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {

        String keyword = txt_search.getText().trim();

        if (keyword.isEmpty()) {
                refreshData();
        } else {
                searchSpaces();
        }
        }

        private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {
        openAddSpaceDialog();
        }

        private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {
        openEditSpaceDialog();
        }

        private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
        deleteSpace();
        }

        private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {
        closeSpaceDialog();
        }

        private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {
        saveSpace();
        }

        private void txt_space_numberActionPerformed(java.awt.event.ActionEvent evt) {
        // can remain empty
        }

        private void cmb_space_typeActionPerformed(java.awt.event.ActionEvent evt) {
        // can remain empty
        }

        private void configureSpacePanel() {

        tbl_spaces.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION
        );

        tbl_spaces
                .getTableHeader()
                .setReorderingAllowed(false);

        tbl_spaces.setRowHeight(25);

        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        }
        
        private void configureSpaceDialog() {

        space_dialog.setModal(true);

        space_dialog.setResizable(false);

        space_dialog.setTitle(
                "Parking Space"
        );

        space_dialog.setDefaultCloseOperation(
                javax.swing.WindowConstants.HIDE_ON_CLOSE
        );

        space_dialog.setSize(
                400,
                300
        );
        }
        
        private void configureEvents() {

        tbl_spaces
                .getSelectionModel()
                .addListSelectionListener(evt -> {

                        if (!evt.getValueIsAdjusting()) {

                        boolean selected =
                                tbl_spaces.getSelectedRow()
                                != -1;

                        btn_edit.setEnabled(selected);
                        btn_delete.setEnabled(selected);
                        }
                });
        }
        
        private void loadSpaces() {

        List<parking_space_model> spaces =
                spaceDAO.getAllSpaces();

        displaySpaces(spaces);
        }
        
        private void displaySpaces(
                List<parking_space_model> spaces) {

        DefaultTableModel tableModel =
                (DefaultTableModel)
                        tbl_spaces.getModel();

        tableModel.setRowCount(0);

        for (parking_space_model space : spaces) {

                tableModel.addRow(
                        new Object[]{
                        space.getSpace_id(),
                        space.getSpace_number(),
                        space.getSpace_type(),
                        space.getStatus()
                        }
                );
        }

        tbl_spaces.clearSelection();

        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        }
        
        private void openAddSpaceDialog() {

        editMode = false;
        selectedSpaceId = -1;

        clearSpaceForm();

        space_dialog.setTitle(
                "Add Parking Space"
        );

        btn_save.setText("Save");

        if (cmb_space_type.getItemCount() > 0) {
                cmb_space_type.setSelectedIndex(0);
        }

        space_dialog.setLocationRelativeTo(this);
        space_dialog.setVisible(true);

        txt_space_number.requestFocusInWindow();
        }
        
        private void saveSpace() {

        String spaceNumber =
                txt_space_number
                        .getText()
                        .trim()
                        .toUpperCase();

        if (spaceNumber.isEmpty()) {

                showValidationError(
                        "Space number is required."
                );

                return;
        }

        if (!spaceNumber.matches(
                "[A-Z0-9\\-]{1,12}"
        )) {

                showValidationError(
                        "Enter a valid space number."
                );

                return;
        }

        if (cmb_space_type.getSelectedItem()
                == null) {

                JOptionPane.showMessageDialog(
                        space_dialog,
                        "Please select a space type.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }

        String spaceType =
                cmb_space_type
                        .getSelectedItem()
                        .toString();

        Integer excludedSpaceId =
                editMode
                        ? selectedSpaceId
                        : null;

        if (spaceDAO.spaceNumberExists(
                spaceNumber,
                excludedSpaceId)) {

                showValidationError(
                        "This space number already exists."
                );

                return;
        }

        if (editMode) {

                updateSpace(
                        spaceNumber,
                        spaceType
                );

        } else {

                addSpace(
                        spaceNumber,
                        spaceType
                );
        }
        }
        
        private void addSpace(
                String spaceNumber,
                String spaceType) {

        parking_space_model space =
                new parking_space_model(
                        spaceNumber,
                        spaceType
                );

        boolean success =
                spaceDAO.addSpace(space);

        if (success) {

                JOptionPane.showMessageDialog(
                        space_dialog,
                        "Parking space added successfully.",
                        "Add Space",
                        JOptionPane.INFORMATION_MESSAGE
                );

                closeSpaceDialog();

                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        space_dialog,
                        "Unable to add parking space.",
                        "Add Space Error",
                        JOptionPane.ERROR_MESSAGE
                );
        }
        }
        
        private void openEditSpaceDialog() {

        int selectedRow =
                tbl_spaces.getSelectedRow();

        if (selectedRow == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select a parking space first.",
                        "No Space Selected",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }

        selectedSpaceId =
                Integer.parseInt(
                        tbl_spaces
                                .getValueAt(
                                        selectedRow,
                                        0
                                )
                                .toString()
                );

        parking_space_model space =
                spaceDAO.getSpaceById(
                        selectedSpaceId
                );

        if (space == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Parking space could not be found.",
                        "Space Error",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
        }

        /*
        * Don't allow an occupied space's type
        * to be modified.
        */
        if ("OCCUPIED".equals(
                space.getStatus())) {

                JOptionPane.showMessageDialog(
                        this,
                        "This parking space is currently occupied.\n"
                        + "Complete the vehicle exit before editing it.",
                        "Space Occupied",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }

        editMode = true;

        txt_space_number.setText(
                space.getSpace_number()
        );

        cmb_space_type.setSelectedItem(
                space.getSpace_type()
        );

        space_dialog.setTitle(
                "Edit Parking Space"
        );

        btn_save.setText(
                "Update"
        );

        space_dialog.setLocationRelativeTo(this);
        space_dialog.setVisible(true);
        }
        
        private void updateSpace(
                String spaceNumber,
                String spaceType) {

        parking_space_model existing =
                spaceDAO.getSpaceById(
                        selectedSpaceId
                );

        if (existing == null) {

                JOptionPane.showMessageDialog(
                        space_dialog,
                        "Parking space could not be found.",
                        "Update Space",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
        }

        parking_space_model space =
                new parking_space_model(
                        selectedSpaceId,
                        spaceNumber,
                        spaceType,
                        existing.getStatus()
                );

        boolean success =
                spaceDAO.updateSpace(space);

        if (success) {

                JOptionPane.showMessageDialog(
                        space_dialog,
                        "Parking space updated successfully.",
                        "Update Space",
                        JOptionPane.INFORMATION_MESSAGE
                );

                closeSpaceDialog();
                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        space_dialog,
                        "Unable to update parking space.",
                        "Update Space Error",
                        JOptionPane.ERROR_MESSAGE
                );
        }
        }
        
        private void deleteSpace() {

        int selectedRow =
                tbl_spaces.getSelectedRow();

        if (selectedRow == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select a parking space first.",
                        "No Space Selected",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }

        int spaceId =
                Integer.parseInt(
                        tbl_spaces
                                .getValueAt(
                                        selectedRow,
                                        0
                                )
                                .toString()
                );

        String spaceNumber =
                tbl_spaces
                        .getValueAt(
                                selectedRow,
                                1
                        )
                        .toString();

        String status =
                tbl_spaces
                        .getValueAt(
                                selectedRow,
                                3
                        )
                        .toString();

        if ("OCCUPIED".equals(status)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Space " + spaceNumber
                        + " is currently occupied.\n"
                        + "Complete the vehicle exit first.",
                        "Space Occupied",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }

        /*
        * Your parking_sessions table uses
        * ON DELETE RESTRICT.
        *
        * Therefore even old completed sessions
        * should prevent deleting this space.
        */
        if (spaceDAO.spaceHasParkingRecords(
                spaceId)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Cannot delete space "
                        + spaceNumber
                        + ".\n\n"
                        + "Parking history exists for this space.",
                        "Space Has Parking Records",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }

        int confirmation =
                JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to delete "
                        + spaceNumber + "?",
                        "Delete Parking Space",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

        if (confirmation
                != JOptionPane.YES_OPTION) {

                return;
        }

        boolean success =
                spaceDAO.deleteSpace(
                        spaceId
                );

        if (success) {

                JOptionPane.showMessageDialog(
                        this,
                        "Parking space deleted successfully.",
                        "Delete Space",
                        JOptionPane.INFORMATION_MESSAGE
                );

                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Unable to delete parking space.",
                        "Delete Space Error",
                        JOptionPane.ERROR_MESSAGE
                );
        }
        }
        
        private void searchSpaces() {

        String keyword =
                txt_search
                        .getText()
                        .trim();

        List<parking_space_model> spaces;

        if (keyword.isEmpty()) {

                spaces =
                        spaceDAO.getAllSpaces();

        } else {

                spaces =
                        spaceDAO.searchSpaces(
                                keyword
                        );
        }

        displaySpaces(spaces);
        }
        
        private void clearSpaceForm() {

        txt_space_number.setText("");

        if (cmb_space_type.getItemCount() > 0) {
                cmb_space_type.setSelectedIndex(0);
        }
        }

        private void closeSpaceDialog() {

        space_dialog.setVisible(false);

        clearSpaceForm();

        editMode = false;
        selectedSpaceId = -1;
        }

        private void showValidationError(
                String message) {

        JOptionPane.showMessageDialog(
                space_dialog,
                message,
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        txt_space_number.requestFocusInWindow();
        }

        public void refreshData() {

        txt_search.setText("");

        loadSpaces();
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cmb_space_type;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog space_dialog;
    private javax.swing.JTable tbl_spaces;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_space_number;
    // End of variables declaration//GEN-END:variables
}