/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import dao.vehicle_exit_dao;
import model.vehicle_exit_model;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author cyber
 */
public class vehicle_exit_panel extends javax.swing.JPanel {
        private final vehicle_exit_dao exitDAO = new vehicle_exit_dao();
        private List<vehicle_exit_model> activeSessions = new ArrayList<>();
        private vehicle_exit_model selectedSession = null;
        private Timestamp calculatedExitTime = null;
        private BigDecimal calculatedParkingFee = null;
        private final Timer refreshTimer;

        public vehicle_exit_panel() {
                initComponents();
                configurePanel();
                refreshData();
                refreshTimer = new Timer(5000, evt -> refreshAvailableVehicles());
                refreshTimer.start();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                content_panel = new javax.swing.JPanel();
                cmb_vehicle = new javax.swing.JComboBox<>();
                txt_owner = new javax.swing.JTextField();
                txt_vehicle_type = new javax.swing.JTextField();
                txt_space = new javax.swing.JTextField();
                txt_entry_time = new javax.swing.JTextField();
                txt_exit_time = new javax.swing.JTextField();
                txt_hourly_rate = new javax.swing.JTextField();
                txt_duration = new javax.swing.JTextField();
                txt_parking_fee = new javax.swing.JTextField();
                btn_clear = new javax.swing.JButton();
                btn_vehicle_exit = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                content_panel.setBackground(new java.awt.Color(0, 0, 0));
                content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                cmb_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                cmb_vehicle.addActionListener(this::cmb_vehicleActionPerformed);
                content_panel.add(cmb_vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, -1));

                txt_owner.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 320, -1));

                txt_vehicle_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_vehicle_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 320, -1));

                txt_space.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_space, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 320, -1));

                txt_entry_time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_entry_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, -1));

                txt_exit_time.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_exit_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 320, -1));

                txt_hourly_rate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_hourly_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 320, -1));

                txt_duration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 320, -1));

                txt_parking_fee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                content_panel.add(txt_parking_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 320, -1));

                btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_clear.setText("Clear");
                btn_clear.addActionListener(this::btn_clearActionPerformed);
                content_panel.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

                btn_vehicle_exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                btn_vehicle_exit.setText("Exit");
                btn_vehicle_exit.addActionListener(this::btn_vehicle_exitActionPerformed);
                content_panel.add(btn_vehicle_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("EXIT");
                content_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Parking Fee");
                content_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 140, -1));

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Hourly Rate");
                content_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 140, -1));

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Parking Space");
                content_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Exit Time");
                content_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Entry Time");
                content_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 140, -1));

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Parked Vehicle");
                content_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Owner");
                content_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 140, -1));

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Vehicle Type");
                content_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, -1));

                jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText("Duration");
                content_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 140, -1));

                add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
        }// </editor-fold>//GEN-END:initComponents

        private void cmb_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_vehicleActionPerformed
                // TODO add your handling code here:
                vehicleSelectionChanged();
        }//GEN-LAST:event_cmb_vehicleActionPerformed

        private void btn_vehicle_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vehicle_exitActionPerformed
                // TODO add your handling code here:
                processVehicleExit();
        }//GEN-LAST:event_btn_vehicle_exitActionPerformed

        private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
                // TODO add your handling code here:
                clearForm();
        }//GEN-LAST:event_btn_clearActionPerformed

        private void configurePanel() {

        txt_owner.setEditable(false);
        txt_vehicle_type.setEditable(false);
        txt_space.setEditable(false);
        txt_entry_time.setEditable(false);
        txt_exit_time.setEditable(false);
        txt_hourly_rate.setEditable(false);
        txt_duration.setEditable(false);
        txt_parking_fee.setEditable(false);

        clearDetails();

        btn_vehicle_exit.setEnabled(false);
        }
        
        private void loadActiveVehicles() {

        activeSessions =
                exitDAO.getActiveParkingSessions();

        cmb_vehicle.removeAllItems();

        cmb_vehicle.addItem(
                "-- Select Parked Vehicle --"
        );

        for (vehicle_exit_model session
                : activeSessions) {

                String display =
                        session.getRegistration_number()
                        + " - "
                        + session.getSpace_number();

                cmb_vehicle.addItem(display);
        }

        cmb_vehicle.setSelectedIndex(0);

        clearDetails();

        btn_vehicle_exit.setEnabled(false);
        }
        
        private void vehicleSelectionChanged() {

        int selectedIndex =
                cmb_vehicle.getSelectedIndex();

        if (selectedIndex <= 0) {

                selectedSession = null;

                clearDetails();

                btn_vehicle_exit.setEnabled(false);

                return;
        }

        selectedSession =
                activeSessions.get(
                        selectedIndex - 1
                );

        displaySessionDetails();
        }
        
        private void displaySessionDetails() {

        if (selectedSession == null) {
                return;
        }

        txt_owner.setText(
                selectedSession.getCustomer_name()
        );

        txt_vehicle_type.setText(
                selectedSession.getVehicle_type()
        );

        txt_space.setText(
                selectedSession.getSpace_number()
        );


        SimpleDateFormat format =
                new SimpleDateFormat(
                        "yyyy-MM-dd HH:mm:ss"
                );

        txt_entry_time.setText(
                format.format(
                        selectedSession.getEntry_time()
                )
        );


        txt_hourly_rate.setText(
                selectedSession
                        .getHourly_rate()
                        .setScale(
                                2,
                                RoundingMode.HALF_UP
                        )
                        .toPlainString()
        );


        calculateExitPreview();

        btn_vehicle_exit.setEnabled(true);
        }
        
        private void calculateExitPreview() {

        if (selectedSession == null) {
                return;
        }


        calculatedExitTime =
                new Timestamp(
                        System.currentTimeMillis()
                );


        Timestamp entryTime =
                selectedSession.getEntry_time();


        long durationMillis =
                calculatedExitTime.getTime()
                - entryTime.getTime();


        if (durationMillis < 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Invalid parking time detected.",
                        "Time Error",
                        JOptionPane.ERROR_MESSAGE
                );

                btn_vehicle_exit.setEnabled(false);

                return;
        }


        /*
        * Round partial minutes upward.
        *
        * Example:
        * 2 min 10 sec -> 3 minutes.
        */
        long totalMinutes =
                (durationMillis + 59999)
                / 60000;


        /*
        * Minimum parking duration for billing:
        * one minute.
        */
        if (totalMinutes < 1) {
                totalMinutes = 1;
        }


        long hours =
                totalMinutes / 60;

        long minutes =
                totalMinutes % 60;


        txt_duration.setText(
                hours + "h "
                + minutes + "m"
        );


        BigDecimal minutesDecimal =
                BigDecimal.valueOf(
                        totalMinutes
                );


        calculatedParkingFee =
                selectedSession
                        .getHourly_rate()
                        .multiply(
                                minutesDecimal
                        )
                        .divide(
                                BigDecimal.valueOf(60),
                                2,
                                RoundingMode.HALF_UP
                        );


        /*
        * Database CHECK allows zero, but because
        * we bill at least one minute this should
        * normally be > 0 when rate > 0.
        */
        txt_parking_fee.setText(
                calculatedParkingFee
                        .setScale(
                                2,
                                RoundingMode.HALF_UP
                        )
                        .toPlainString()
        );


        SimpleDateFormat format =
                new SimpleDateFormat(
                        "yyyy-MM-dd HH:mm:ss"
                );


        txt_exit_time.setText(
                format.format(
                        calculatedExitTime
                )
        );
        }
        
        private void processVehicleExit() {

        if (selectedSession == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select a parked vehicle.",
                        "No Vehicle Selected",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        /*
        * Re-fetch from database.
        *
        * This makes sure the session is still ACTIVE.
        */
        vehicle_exit_model currentSession =
                exitDAO.getActiveSessionById(
                        selectedSession.getSession_id()
                );


        if (currentSession == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "This parking session is no longer active.",
                        "Session Changed",
                        JOptionPane.WARNING_MESSAGE
                );

                refreshData();

                return;
        }


        /*
        * Replace our old in-memory session with
        * current database data.
        */
        selectedSession = currentSession;


        /*
        * Recalculate using the actual confirmation
        * time instead of an old preview time.
        */
        calculateExitPreview();


        if (calculatedExitTime == null
                || calculatedParkingFee == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Unable to calculate parking fee.",
                        "Exit Error",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
        }


        int confirmation =
                JOptionPane.showConfirmDialog(
                        this,

                        "Complete vehicle exit?\n\n"
                        + "Vehicle: "
                        + selectedSession
                                .getRegistration_number()
                        + "\n"
                        + "Owner: "
                        + selectedSession
                                .getCustomer_name()
                        + "\n"
                        + "Space: "
                        + selectedSession
                                .getSpace_number()
                        + "\n"
                        + "Duration: "
                        + txt_duration.getText()
                        + "\n"
                        + "Hourly Rate: "
                        + txt_hourly_rate.getText()
                        + "\n"
                        + "Parking Fee: "
                        + txt_parking_fee.getText(),

                        "Confirm Vehicle Exit",

                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );


        if (confirmation
                != JOptionPane.YES_OPTION) {

                return;
        }


        /*
        * User may have spent time reading the
        * confirmation dialog.
        *
        * Recalculate one final time before saving.
        */
        calculateExitPreview();


        boolean success =
                exitDAO.completeVehicleExit(
                        selectedSession
                                .getSession_id(),

                        selectedSession
                                .getSpace_id(),

                        calculatedExitTime,

                        calculatedParkingFee
                );


        if (success) {

                JOptionPane.showMessageDialog(
                        this,

                        "Vehicle exit completed successfully.\n\n"
                        + "Vehicle: "
                        + selectedSession
                                .getRegistration_number()
                        + "\n"
                        + "Space: "
                        + selectedSession
                                .getSpace_number()
                        + "\n"
                        + "Parking Fee: "
                        + calculatedParkingFee
                                .setScale(
                                        2,
                                        RoundingMode.HALF_UP
                                )
                                .toPlainString(),

                        "Vehicle Exit Successful",

                        JOptionPane.INFORMATION_MESSAGE
                );


                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        this,

                        "Unable to complete vehicle exit.\n\n"
                        + "The parking session or space "
                        + "may have changed.",

                        "Vehicle Exit Failed",

                        JOptionPane.ERROR_MESSAGE
                );


                refreshData();
        }
        }
        
        private void clearForm() {

        selectedSession = null;

        calculatedExitTime = null;
        calculatedParkingFee = null;


        if (cmb_vehicle.getItemCount() > 0) {
                cmb_vehicle.setSelectedIndex(0);
        }


        clearDetails();

        btn_vehicle_exit.setEnabled(false);
        }
        
        private void clearDetails() {

        txt_owner.setText("");
        txt_vehicle_type.setText("");

        txt_space.setText("");

        txt_entry_time.setText("");
        txt_exit_time.setText("");

        txt_hourly_rate.setText("");

        txt_duration.setText("");
        txt_parking_fee.setText("");

        calculatedExitTime = null;
        calculatedParkingFee = null;
        }
        
        public void refreshData() {

        selectedSession = null;

        calculatedExitTime = null;
        calculatedParkingFee = null;

        loadActiveVehicles();
        }

        /**
         * Keeps the available-session list current without interrupting a user
         * who has already selected a vehicle and may be confirming its exit.
         */
        private void refreshAvailableVehicles() {
                if (isShowing() && selectedSession == null) {
                        loadActiveVehicles();
                }
        }
        
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_clear;
        private javax.swing.JButton btn_vehicle_exit;
        private javax.swing.JComboBox<String> cmb_vehicle;
        private javax.swing.JPanel content_panel;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JTextField txt_duration;
        private javax.swing.JTextField txt_entry_time;
        private javax.swing.JTextField txt_exit_time;
        private javax.swing.JTextField txt_hourly_rate;
        private javax.swing.JTextField txt_owner;
        private javax.swing.JTextField txt_parking_fee;
        private javax.swing.JTextField txt_space;
        private javax.swing.JTextField txt_vehicle_type;
        // End of variables declaration//GEN-END:variables
}
