/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels;

import dao.customer_dao;
import dao.vehicle_dao;
import model.customer_model;
import model.vehicle_model;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyber
 */
public class vehicles_panel extends javax.swing.JPanel {
        private final vehicle_dao vehicleDAO = new vehicle_dao();
        private final customer_dao customerDAO = new customer_dao();
        private boolean editMode = false;
        private int selectedVehicleId = -1;

        public vehicles_panel() {
                initComponents();
                configureVehiclePanel();
                configureVehicleDialog();
                configureEvents();
                loadCustomersToComboBox();
                loadVehicles();
                refreshData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicle_dialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        cmb_owner = new javax.swing.JComboBox<>();
        txt_registration = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox<>();
        txt_brand = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vehicles = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();

        vehicle_dialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_owner.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmb_owner.addActionListener(this::cmb_ownerActionPerformed);
        jPanel2.add(cmb_owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        txt_registration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_registration.addActionListener(this::txt_registrationActionPerformed);
        jPanel2.add(txt_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, -1));

        cmb_type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAR", "MOTORCYCLE", "VAN" }));
        cmb_type.addActionListener(this::cmb_typeActionPerformed);
        jPanel2.add(cmb_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 170, -1));

        txt_brand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_brand.addActionListener(this::txt_brandActionPerformed);
        jPanel2.add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        txt_model.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_model.addActionListener(this::txt_modelActionPerformed);
        jPanel2.add(txt_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, -1));

        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(this::btn_cancelActionPerformed);
        jPanel2.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(this::btn_saveActionPerformed);
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Type");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Owner");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Brand");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Model");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registration No");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        vehicle_dialog.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content_panel.setBackground(new java.awt.Color(0, 0, 0));
        content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_vehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Registration ", "Type", "Brand", "Model", "Owner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_vehicles);
        if (tbl_vehicles.getColumnModel().getColumnCount() > 0) {
            tbl_vehicles.getColumnModel().getColumn(0).setResizable(false);
            tbl_vehicles.getColumnModel().getColumn(1).setResizable(false);
            tbl_vehicles.getColumnModel().getColumn(2).setResizable(false);
            tbl_vehicles.getColumnModel().getColumn(3).setResizable(false);
            tbl_vehicles.getColumnModel().getColumn(4).setResizable(false);
            tbl_vehicles.getColumnModel().getColumn(5).setResizable(false);
        }

        content_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 700, 300));

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setText("add");
        btn_add.addActionListener(this::btn_addActionPerformed);
        content_panel.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 80, -1));

        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_edit.setText("edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);
        content_panel.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 80, -1));

        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_delete.setText("delete");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);
        content_panel.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VEHICLE");
        content_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Search Query");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, -1));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(this::btn_searchActionPerformed);
        jPanel3.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_search.addActionListener(this::txt_searchActionPerformed);
        jPanel3.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, -1));

        content_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 70));

        add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
    }// </editor-fold>//GEN-END:initComponents

        private void cmb_ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ownerActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_cmb_ownerActionPerformed

        private void txt_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registrationActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_registrationActionPerformed

        private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_cmb_typeActionPerformed

        private void txt_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_brandActionPerformed

        private void txt_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modelActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt_modelActionPerformed

        private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {
        closeVehicleDialog();
        }

        private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {
        saveVehicle();
        }

        private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = txt_search.getText().trim();

        if (keyword.isEmpty()) {
                refreshData();
        } else {
                searchVehicles();
        }
        }

        private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {
        searchVehicles();
        }

        private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {
        openAddVehicleDialog();
        }

        private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {
        openEditVehicleDialog();
        }

        private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
        deleteVehicle();
        }

        private void configureVehiclePanel() {

        tbl_vehicles.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION
        );

        tbl_vehicles
                .getTableHeader()
                .setReorderingAllowed(false);

        tbl_vehicles.setRowHeight(25);

        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        }
        
        private void configureVehicleDialog() {

        vehicle_dialog.setModal(true);

        vehicle_dialog.setResizable(false);

        vehicle_dialog.setTitle("Vehicle");

        vehicle_dialog.setDefaultCloseOperation(
                javax.swing.WindowConstants.HIDE_ON_CLOSE
        );

        vehicle_dialog.setSize(
                420,
                440
        );
        }
        
        private void configureEvents() {
        // Button handlers are already connected by initComponents(). Registering
        // them again here makes every click run twice (including two inserts).
        tbl_vehicles
                .getSelectionModel()
                .addListSelectionListener(evt -> {

                        if (!evt.getValueIsAdjusting()) {

                        boolean selected =
                                tbl_vehicles.getSelectedRow() != -1;

                        btn_edit.setEnabled(selected);

                        btn_delete.setEnabled(selected);
                        }
                });
        }
        
        private void loadCustomersToComboBox() {

        cmb_owner.removeAllItems();

        List<customer_model> customers =
                customerDAO.getAllCustomers();

        for (customer_model customer : customers) {

                String item =
                        customer.get_customer_model_customer_id()
                        + " - "
                        + customer.get_customer_model_name();

                cmb_owner.addItem(item);
        }
        }
        
        private void loadVehicles() {

        List<vehicle_model> vehicles =
                vehicleDAO.getAllVehicles();

        displayVehicles(vehicles);
        }
        
        private void displayVehicles(
                List<vehicle_model> vehicles) {

        DefaultTableModel tableModel =
                (DefaultTableModel)
                        tbl_vehicles.getModel();

        tableModel.setRowCount(0);

        SimpleDateFormat dateFormat =
                new SimpleDateFormat(
                        "yyyy-MM-dd HH:mm"
                );

        for (vehicle_model vehicle : vehicles) {

                Timestamp createdAt =
                        vehicle.getCreated_at();

                String registered = "";

                if (createdAt != null) {

                registered =
                        dateFormat.format(
                                createdAt
                        );
                }

                tableModel.addRow(
                        new Object[]{
                        vehicle.getVehicle_id(),
                        vehicle.getRegistration_number(),
                        vehicle.getVehicle_type(),
                        vehicle.getBrand(),
                        vehicle.getModel(),
                        vehicle.getCustomer_name(),
                        registered
                        }
                );
        }

        tbl_vehicles.clearSelection();

        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        }
        
        private void searchVehicles() {

        String keyword =
                txt_search
                        .getText()
                        .trim();

        List<vehicle_model> vehicles;

        if (keyword.isEmpty()) {

                vehicles =
                        vehicleDAO.getAllVehicles();

        } else {

                vehicles =
                        vehicleDAO.searchVehicles(
                                keyword
                        );
        }

        displayVehicles(vehicles);
        }
        
        private void openAddVehicleDialog() {

        editMode = false;

        selectedVehicleId = -1;

        clearVehicleForm();

        loadCustomersToComboBox();

        vehicle_dialog.setTitle(
                "Add Vehicle"
        );

        btn_save.setText(
                "Save"
        );

        if (cmb_type.getItemCount() > 0) {
                cmb_type.setSelectedIndex(0);
        }

        if (cmb_owner.getItemCount() > 0) {
                cmb_owner.setSelectedIndex(0);
        }

        vehicle_dialog.setLocationRelativeTo(
                this
        );

        vehicle_dialog.setVisible(
                true
        );

        txt_registration.requestFocusInWindow();
        }
        
        private void saveVehicle() {

        String registration =
                txt_registration
                        .getText()
                        .trim()
                        .toUpperCase();

        String brand =
                txt_brand
                        .getText()
                        .trim();

        String model =
                txt_model
                        .getText()
                        .trim();


        if (cmb_owner.getSelectedItem() == null) {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Please select a customer.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        if (registration.isEmpty()) {

                showValidationError(
                        "Registration number is required.",
                        txt_registration
                );

                return;
        }


        if (!registration.matches(
                "[A-Z0-9\\-]{2,20}"
        )) {

                showValidationError(
                        "Enter a valid registration number.",
                        txt_registration
                );

                return;
        }


        if (cmb_type.getSelectedItem() == null) {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Please select a vehicle type.",
                        "Validation Error",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        if (brand.isEmpty()) {

                showValidationError(
                        "Vehicle brand is required.",
                        txt_brand
                );

                return;
        }


        if (model.isEmpty()) {

                showValidationError(
                        "Vehicle model is required.",
                        txt_model
                );

                return;
        }


        Integer excludedVehicleId =
                editMode
                        ? selectedVehicleId
                        : null;


        if (vehicleDAO.registrationExists(
                registration,
                excludedVehicleId)) {

                showValidationError(
                        "This registration number already exists.",
                        txt_registration
                );

                return;
        }


        String selectedCustomer =
                cmb_owner.getSelectedItem().toString();

        int customerId =
                Integer.parseInt(
                        selectedCustomer
                                .substring(
                                        0,
                                        selectedCustomer.indexOf(" - ")
                                )
                );

        String vehicleType =
                cmb_type.getSelectedItem().toString();


        if (editMode) {

                updateVehicle(
                        registration,
                        vehicleType,
                        brand,
                        model,
                        customerId
                );

        } else {

                addVehicle(
                        registration,
                        vehicleType,
                        brand,
                        model,
                        customerId
                );
        }
        }
        
        private void addVehicle(
                String registration,
                String vehicleType,
                String brand,
                String model,
                int customerId) {

        vehicle_model vehicle =
                new vehicle_model(
                        registration,
                        vehicleType,
                        brand,
                        model,
                        customerId
                );

        boolean success =
                vehicleDAO.addVehicle(
                        vehicle
                );

        if (success) {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Vehicle added successfully.",
                        "Add Vehicle",
                        JOptionPane.INFORMATION_MESSAGE
                );

                closeVehicleDialog();

                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Unable to add vehicle.",
                        "Add Vehicle Error",
                        JOptionPane.ERROR_MESSAGE
                );
        }
        }
        
        private void openEditVehicleDialog() {

        int selectedRow =
                tbl_vehicles.getSelectedRow();

        if (selectedRow == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select a vehicle first.",
                        "No Vehicle Selected",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        selectedVehicleId =
                Integer.parseInt(
                        tbl_vehicles
                                .getValueAt(
                                        selectedRow,
                                        0
                                )
                                .toString()
                );


        vehicle_model vehicle =
                vehicleDAO.getVehicleById(
                        selectedVehicleId
                );


        if (vehicle == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Vehicle could not be found.",
                        "Vehicle Error",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
        }


        editMode = true;

        loadCustomersToComboBox();


        txt_registration.setText(
                vehicle.getRegistration_number()
        );

        txt_brand.setText(
                vehicle.getBrand()
        );

        txt_model.setText(
                vehicle.getModel()
        );


        cmb_type.setSelectedItem(
                vehicle.getVehicle_type()
        );


        selectCustomer(
                vehicle.getCustomer_id()
        );


        vehicle_dialog.setTitle(
                "Edit Vehicle"
        );

        btn_save.setText(
                "Update"
        );


        vehicle_dialog.setLocationRelativeTo(
                this
        );

        vehicle_dialog.setVisible(
                true
        );
        }
        
        private void selectCustomer(int customerId) {

        String prefix = customerId + " - ";

        for (int i = 0; i < cmb_owner.getItemCount(); i++) {

                String item = cmb_owner.getItemAt(i);

                if (item != null && item.startsWith(prefix)) {
                cmb_owner.setSelectedIndex(i);
                return;
                }
        }
        }
        
        private void updateVehicle(
                String registration,
                String vehicleType,
                String brand,
                String model,
                int customerId) {

        vehicle_model existing =
                vehicleDAO.getVehicleById(
                        selectedVehicleId
                );

        if (existing == null) {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Vehicle could not be found.",
                        "Update Vehicle",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
        }


        vehicle_model vehicle =
                new vehicle_model(

                        selectedVehicleId,

                        registration,

                        vehicleType,

                        brand,

                        model,

                        customerId,

                        existing.getCustomer_name(),

                        existing.getCreated_at()
                );


        boolean success =
                vehicleDAO.updateVehicle(
                        vehicle
                );


        if (success) {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Vehicle updated successfully.",
                        "Update Vehicle",
                        JOptionPane.INFORMATION_MESSAGE
                );

                closeVehicleDialog();

                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        vehicle_dialog,
                        "Unable to update vehicle.",
                        "Update Vehicle Error",
                        JOptionPane.ERROR_MESSAGE
                );
        }
        }
        
        private void deleteVehicle() {

        int selectedRow =
                tbl_vehicles.getSelectedRow();


        if (selectedRow == -1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Please select a vehicle first.",
                        "No Vehicle Selected",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        int vehicleId =
                Integer.parseInt(
                        tbl_vehicles
                                .getValueAt(
                                        selectedRow,
                                        0
                                )
                                .toString()
                );


        String registration =
                tbl_vehicles
                        .getValueAt(
                                selectedRow,
                                1
                        )
                        .toString();


        /*
        * Only keep this check if your DB really
        * has parking_sessions.
        */
        if (vehicleDAO.vehicleHasActiveParking(
                vehicleId)) {

                JOptionPane.showMessageDialog(
                        this,

                        "Cannot delete vehicle "
                        + registration
                        + ".\n\n"
                        + "The vehicle is currently parked. Complete its exit first.",

                        "Vehicle Has Parking Records",

                        JOptionPane.WARNING_MESSAGE
                );

                return;
        }


        int confirmation =
                JOptionPane.showConfirmDialog(
                        this,

                        "Are you sure you want to permanently delete "
                        + registration
                        + "?\n\nCompleted parking history for this vehicle will also be deleted.",

                        "Delete Vehicle",

                        JOptionPane.YES_NO_OPTION,

                        JOptionPane.WARNING_MESSAGE
                );


        if (
                confirmation
                        != JOptionPane.YES_OPTION
        ) {

                return;
        }


        boolean success =
                vehicleDAO.deleteVehicle(
                        vehicleId
                );


        if (success) {

                JOptionPane.showMessageDialog(
                        this,
                        "Vehicle deleted successfully.",
                        "Delete Vehicle",
                        JOptionPane.INFORMATION_MESSAGE
                );

                refreshData();

        } else {

                JOptionPane.showMessageDialog(
                        this,

                        "Unable to delete vehicle.\n"
                        + "The vehicle may still have active parking, "
                        + "or the database operation failed.",

                        "Delete Vehicle Error",

                        JOptionPane.ERROR_MESSAGE
                );
        }
        }
        
        private void clearVehicleForm() {

        txt_registration.setText("");

        txt_brand.setText("");

        txt_model.setText("");

        if (cmb_owner.getItemCount() > 0) {
                cmb_owner.setSelectedIndex(0);
        }

        if (cmb_type.getItemCount() > 0) {
                cmb_type.setSelectedIndex(0);
        }
        }
        
        private void closeVehicleDialog() {

        vehicle_dialog.setVisible(false);

        clearVehicleForm();

        editMode = false;

        selectedVehicleId = -1;
        }
        
        private void showValidationError(
                String message,
                javax.swing.JTextField field) {

        JOptionPane.showMessageDialog(
                vehicle_dialog,
                message,
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
        );

        field.requestFocusInWindow();
        }
        
        public void refreshData() {

        txt_search.setText("");

        loadCustomersToComboBox();

        loadVehicles();
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cmb_owner;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_vehicles;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_registration;
    private javax.swing.JTextField txt_search;
    private javax.swing.JDialog vehicle_dialog;
    // End of variables declaration//GEN-END:variables
}
