/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import ui.panels.dashboard_panel;
import ui.panels.customers_panel;
import ui.panels.spaces_panel;
import ui.panels.park_vehicle_panel;
import ui.panels.vehicle_exit_panel;
import ui.panels.active_panel;
import ui.panels.history_panel;
import ui.panels.vehicles_panel;

/**
 *
 * @author cyber
 */
public class dashboard_frame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard_frame.class.getName());
    private dashboard_panel dashboardPanel;
    private customers_panel customersPanel;
    private spaces_panel spacesPanel;
    private park_vehicle_panel parkVehiclePanel;
    private vehicle_exit_panel vehicleExitPanel;
    private active_panel activePanel;
    private history_panel historyPanel;
    private vehicles_panel vehiclesPanel;

    public dashboard_frame() {
        initComponents();
        setupPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        header_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dash_logout = new javax.swing.JButton();
        sidebar_panel = new javax.swing.JPanel();
        btn_history = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        btn_customers = new javax.swing.JButton();
        btn_spaces = new javax.swing.JButton();
        btn_park_vehicle = new javax.swing.JButton();
        btn_vehicle_exit = new javax.swing.JButton();
        btn_active = new javax.swing.JButton();
        btn_customers1 = new javax.swing.JButton();
        content_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(0, 0, 0));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_panel.setBackground(new java.awt.Color(0, 0, 0));
        header_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        header_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parking System");
        header_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        dash_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dash_logout.setText("Logout");
        dash_logout.addActionListener(this::dash_logoutActionPerformed);
        header_panel.add(dash_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 80, 30));

        main_panel.add(header_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        sidebar_panel.setBackground(new java.awt.Color(0, 0, 0));
        sidebar_panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        sidebar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_history.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_history.setText("History");
        btn_history.addActionListener(this::btn_historyActionPerformed);
        sidebar_panel.add(btn_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));

        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addActionListener(this::btn_dashboardActionPerformed);
        sidebar_panel.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        btn_customers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_customers.setText("Vehicles");
        btn_customers.addActionListener(this::btn_customersActionPerformed);
        sidebar_panel.add(btn_customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        btn_spaces.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_spaces.setText("Spaces");
        btn_spaces.addActionListener(this::btn_spacesActionPerformed);
        sidebar_panel.add(btn_spaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, -1));

        btn_park_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_park_vehicle.setText("Park Vehicle");
        btn_park_vehicle.addActionListener(this::btn_park_vehicleActionPerformed);
        sidebar_panel.add(btn_park_vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        btn_vehicle_exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_vehicle_exit.setText("Vehicle Exit");
        btn_vehicle_exit.addActionListener(this::btn_vehicle_exitActionPerformed);
        sidebar_panel.add(btn_vehicle_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        btn_active.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_active.setText("Active");
        btn_active.addActionListener(this::btn_activeActionPerformed);
        sidebar_panel.add(btn_active, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        btn_customers1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_customers1.setText("Customers");
        btn_customers1.addActionListener(this::btn_customers1ActionPerformed);
        sidebar_panel.add(btn_customers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        main_panel.add(sidebar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 530));

        content_panel.setBackground(new java.awt.Color(0, 0, 0));
        content_panel.setLayout(new java.awt.CardLayout());
        main_panel.add(content_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 720, 480));

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 530));

        setSize(new java.awt.Dimension(883, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        dashboardPanel.refreshData();
        cardLayout.show(content_panel, "dashboard");
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customersActionPerformed
        vehiclesPanel.refreshData();
        cardLayout.show(content_panel, "vehicles");
    }//GEN-LAST:event_btn_customersActionPerformed

    private void btn_spacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spacesActionPerformed
        spacesPanel.refreshData();
        cardLayout.show(content_panel, "spaces");
    }//GEN-LAST:event_btn_spacesActionPerformed

    private void btn_park_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_park_vehicleActionPerformed
        parkVehiclePanel.refreshData();
        cardLayout.show(content_panel, "park_vehicle");
    }//GEN-LAST:event_btn_park_vehicleActionPerformed

    private void btn_vehicle_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vehicle_exitActionPerformed
        vehicleExitPanel.refreshData();
        cardLayout.show(content_panel, "vehicle_exit");
    }//GEN-LAST:event_btn_vehicle_exitActionPerformed

    private void btn_activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_activeActionPerformed
        activePanel.refreshData();
        cardLayout.show(content_panel, "active");
    }//GEN-LAST:event_btn_activeActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        historyPanel.refreshData();
        cardLayout.show(content_panel, "history");
    }//GEN-LAST:event_btn_historyActionPerformed

    private void btn_customers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customers1ActionPerformed
        customersPanel.refreshData();
        cardLayout.show(content_panel, "customers");
    }//GEN-LAST:event_btn_customers1ActionPerformed

    private void dash_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dash_logoutActionPerformed
        // TODO add your handling code here:
        login_frame login = new login_frame();
        login.setVisible(true);

        // Close login window
        this.dispose();
    }//GEN-LAST:event_dash_logoutActionPerformed

    private CardLayout cardLayout;

    private void setupPanels() {

        cardLayout = (CardLayout) content_panel.getLayout();

        dashboardPanel = new dashboard_panel();
        content_panel.add(dashboardPanel, "dashboard");
        customersPanel = new customers_panel();
        content_panel.add(customersPanel, "customers");
        spacesPanel = new spaces_panel();
        content_panel.add(spacesPanel, "spaces");
        parkVehiclePanel = new park_vehicle_panel();
        content_panel.add(parkVehiclePanel, "park_vehicle");
        vehicleExitPanel = new vehicle_exit_panel();
        content_panel.add(vehicleExitPanel, "vehicle_exit");
        activePanel = new active_panel();
        content_panel.add(activePanel, "active");
        historyPanel = new history_panel();
        content_panel.add(historyPanel, "history");
        vehiclesPanel = new vehicles_panel();
        content_panel.add(vehiclesPanel, "vehicles");

        cardLayout.show(content_panel, "dashboard");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard_frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_active;
    private javax.swing.JButton btn_customers;
    private javax.swing.JButton btn_customers1;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_park_vehicle;
    private javax.swing.JButton btn_spaces;
    private javax.swing.JButton btn_vehicle_exit;
    private javax.swing.JPanel content_panel;
    private javax.swing.JButton dash_logout;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel sidebar_panel;
    // End of variables declaration//GEN-END:variables
}
