package ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

/**
 *
 * @author cyber
 */
public class login_frame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login_frame.class.getName());

    /**
     * Creates new form login_frame
     */
    public login_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        user_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_check_box = new javax.swing.JCheckBox();
        user_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parking Management System Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, -1));

        user_name.addActionListener(this::user_nameActionPerformed);
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, -1));

        user_password.addActionListener(this::user_passwordActionPerformed);
        jPanel1.add(user_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 250, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 70, -1));

        user_check_box.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_check_box.setForeground(new java.awt.Color(255, 255, 255));
        user_check_box.setText("Show Password");
        user_check_box.addActionListener(this::user_check_boxActionPerformed);
        jPanel1.add(user_check_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        user_login.setText("Login");
        user_login.addActionListener(this::user_loginActionPerformed);
        jPanel1.add(user_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setSize(new java.awt.Dimension(414, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void user_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_passwordActionPerformed

    private void user_loginActionPerformed(java.awt.event.ActionEvent evt) {                                           
    String username = user_name.getText().trim();
    String password = new String(user_password.getPassword());

    // Check empty fields
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter username and password.",
            "Login Warning",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Hard-coded authentication
    if (username.equals("admin") && password.equals("admin321@")) {

        JOptionPane.showMessageDialog(
            this,
            "Login successful!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );

        // Open dashboard
        dashboard_frame dashboard = new dashboard_frame();
        dashboard.setVisible(true);

        // Close login window
        this.dispose();

    } else {

        JOptionPane.showMessageDialog(
            this,
            "Invalid username or password.",
            "Login Failed",
            JOptionPane.ERROR_MESSAGE
        );

        user_name.setText("");
        user_password.setText("");

        // Put cursor back into username
        user_name.requestFocus();
    }
}//GEN-LAST:event_user_loginActionPerformed

    private void user_check_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_check_boxActionPerformed
        if (user_check_box.isSelected()) {
            user_password.setEchoChar((char)0);
        } else {
            user_password.setEchoChar('•');
        }
    }//GEN-LAST:event_user_check_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login_frame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox user_check_box;
    private javax.swing.JButton user_login;
    private javax.swing.JTextField user_name;
    private javax.swing.JPasswordField user_password;
    // End of variables declaration//GEN-END:variables
}
